- c/DoublyLL.c
HCT-3 (bug) [SonarQube] Define each identifier in a dedicated statement.
> HCT-3 (bug) [SonarQube] Define each identifier in a dedicated statement.

- c/binsearch.c
SCT-2 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "yarr" is "int *".
> SCT-2 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "yarr" is "int *".

- c/DoublyLL.c
SCT-3 (bug) [SonarQube] Define each identifier in a dedicated statement.
> SCT-3 (bug) [SonarQube] Define each identifier in a dedicated statement.

- c/count.c
SCT-11 (bug) [SonarQube] non-void function does not return a value
> SCT-11 (bug) [SonarQube] non-void function does not return a value

- c/even_or_odd.c
SCT-12 (bug) [SonarQube] Use curly braces or indentation to denote the code conditionally executed by this statement.
> SCT-12 (bug) [SonarQube] Use curly braces or indentation to denote the code conditionally executed by this statement.

- c/fac.c
SCT-14 (bug) [SonarQube] code will never be executed
> SCT-14 (bug) [SonarQube] code will never be executed

- c/fib.c
SCT-15 (bug) [SonarQube] Refactor this loop so that it is less error-prone.
> SCT-15 (bug) [SonarQube] Refactor this loop so that it is less error-prone.

- c/insertionsort.c
SCT-16 (bug) [SonarQube] Change this loop body so that it can be executed more than once.
> SCT-16 (bug) [SonarQube] Change this loop body so that it can be executed more than once.

- c/keylogger.c
SCT-17 (bug) [SonarQube] Opened stream never closed. Potential resource leak
> SCT-17 (bug) [SonarQube] Opened stream never closed. Potential resource leak

- c/linearsearch.c
TTT-31 (bug) [SonarQube] non-void function does not return a value in all control paths
> TTT-31 (bug) [SonarQube] non-void function does not return a value in all control paths

- todo-list.c
TTT-3 (bug) [SonarQube] Define each identifier in a dedicated statement.
> TTT-3 (bug) [SonarQube] Define each identifier in a dedicated statement.

- todo-list.c
TTT-4 (bug) [SonarQube] 'return' will never be executed
> TTT-4 (bug) [SonarQube] 'return' will never be executed

- c/binsearch.c
TTT-5 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "yarr" is "int *".
> TTT-5 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "yarr" is "int *".

- c/DoublyLL.c
TTT-6 (bug) [SonarQube] Define each identifier in a dedicated statement.
> TTT-6 (bug) [SonarQube] Define each identifier in a dedicated statement.

- c/InsertionDeletionLinkedList.c
TTT-7 (bug) [SonarQube] Potential leak of memory pointed to by 'NewNode'
> TTT-7 (bug) [SonarQube] Potential leak of memory pointed to by 'NewNode'

- c/InsertionDeletionLinkedList.c
TTT-13 (bug) [SonarQube] Define each identifier in a dedicated statement.
> TTT-13 (bug) [SonarQube] Define each identifier in a dedicated statement.

- c/count.c
TTT-14 (bug) [SonarQube] non-void function does not return a value
> TTT-14 (bug) [SonarQube] non-void function does not return a value

- c/even_or_odd.c
TTT-15 (bug) [SonarQube] Use curly braces or indentation to denote the code conditionally executed by this statement.
> TTT-15 (bug) [SonarQube] Use curly braces or indentation to denote the code conditionally executed by this statement.

- c/even_or_odd.c
TTT-16 (bug) [SonarQube] Use curly braces or indentation to denote the code conditionally executed by this statement.
> TTT-16 (bug) [SonarQube] Use curly braces or indentation to denote the code conditionally executed by this statement.

- c/fac.c
TTT-17 (bug) [SonarQube] code will never be executed
> TTT-17 (bug) [SonarQube] code will never be executed

- c/fib.c
TTT-18 (bug) [SonarQube] Refactor this loop so that it is less error-prone.
> TTT-18 (bug) [SonarQube] Refactor this loop so that it is less error-prone.

- c/insertionsort.c
TTT-19 (bug) [SonarQube] Change this loop body so that it can be executed more than once.
> TTT-19 (bug) [SonarQube] Change this loop body so that it can be executed more than once.

- c/keylogger.c
TTT-20 (bug) [SonarQube] Opened stream never closed. Potential resource leak
> TTT-20 (bug) [SonarQube] Opened stream never closed. Potential resource leak

- c/keylogger.c
TTT-22 (bug) [SonarQube] Stream pointer might be NULL
> TTT-22 (bug) [SonarQube] Stream pointer might be NULL

- c/keylogger.c
TTT-25 (bug) [SonarQube] Stream pointer might be NULL
> TTT-25 (bug) [SonarQube] Stream pointer might be NULL

- c/keylogger.c
TTT-27 (bug) [SonarQube] Opened stream never closed. Potential resource leak
> TTT-27 (bug) [SonarQube] Opened stream never closed. Potential resource leak

- c/linearsearch.c
TTT-28 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "yarr" is "int *".
> TTT-28 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "yarr" is "int *".

- c/linearsearch.c
TTT-29 (bug) [SonarQube] loop will run at most once (loop increment never executed)
> TTT-29 (bug) [SonarQube] loop will run at most once (loop increment never executed)

- c/insertionsort.c
HDS-13 (bug) [SonarQube] Change this loop body so that it can be executed more than once.
> HDS-13 (bug) [SonarQube] Change this loop body so that it can be executed more than once.

- c/InsertionDeletionLinkedList.c
STC-7 (bug) [SonarQube] Potential leak of memory pointed to by 'NewNode'
> STC-7 (bug) [SonarQube] Potential leak of memory pointed to by 'NewNode'

- c/DoublyLL.c
SCP-7 (bug) [SonarQube] Define each identifier in a dedicated statement.
> SCP-7 (bug) [SonarQube] Define each identifier in a dedicated statement.

- c/insertionsort.c
SCP-11 (bug) [SonarQube] Change this loop body so that it can be executed more than once.
> SCP-11 (bug) [SonarQube] Change this loop body so that it can be executed more than once.

- c/mergesort.c
SCP-12 (bug) [SonarQube] Define each identifier in a dedicated statement.
> SCP-12 (bug) [SonarQube] Define each identifier in a dedicated statement.

- c/mergesort.c
SCP-13 (bug) [SonarQube] This statement will not be executed conditionally.
> SCP-13 (bug) [SonarQube] This statement will not be executed conditionally.

- c/selection_sort.c
SCP-17 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "ptr" is "int *".
> SCP-17 (bug) [SonarQube] Make the type of this parameter a pointer-to-const. The current type of "ptr" is "int *".
